django_invwoice/urls.py
from django.contrib import admin
from django.urls import path ,include

from django.conf import settings

from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns (
    path('admin/', admin.site.urls),
    path('',include("fact_app.urls")),
)

if settings.DEBUG:

     urlpatterns  += static(settings.MEDIA_DIR , document_root=settings.MEDIA_DIR)
   

fact_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('add_custumer',views.AddView.as_view(),name='add_customer'),
    path('add_invoice',views.AddInvoiceView.as_view(),name='add_invoice'),
    path('InvoiceDetailView/<int:pk>/',views.InvoiceDetailView.as_view(),name='InvoiceDetailView'),
    path('invoicepdf/<int:pk>/',views.get_invoice_pdf,name='invoice_pdf'),
    # path('post', views.post_view, name='post'), 
]

models.py
from django.db import models
from django.contrib.auth.models import User
from django.views import View
# Modèle représentant un client
class Costumer(models.Model):
    # Types de sexe disponibles pour un client
    Sex_type = (
        (' M ', 'Male'),
        (' F ','Femele'),
         
    )
    
    # Champs du modèle Costumer
    name = models.CharField(max_length=100)  # Nom du client
    email = models.EmailField()  # Email du client
    phone = models.CharField(max_length=15)  # Téléphone du client
    address = models.TextField()  # Adresse du client
    city = models.CharField(max_length=50)  # Ville du client
    state = models.CharField(max_length=50)  # État du client9
    zip_code = models.CharField(max_length=10)  # Code postal du client
    sex = models.CharField(max_length=7, choices=Sex_type)  # Sexe du client
    created_at = models.DateTimeField(auto_now_add=True)  # Date de création du client
    save_b = models.ForeignKey(User, on_delete=models.PROTECT)  # Utilisateur qui a enregistré le client

    class Meta:
        db_table = ''  # Nom de la table dans la base de données
        managed = True  # Indique si Django doit gérer la table
        verbose_name = 'Costumer'  # Nom singulier du modèle
        verbose_name_plural = 'Costumers'  # Nom pluriel du modèle

    def __str__(self):
        return self.name  # Représentation en chaîne de caractères du modèle

# Modèle représentant une facture
class Invoice(models.Model):
    # Statuts disponibles pour une facture
    INNVOICE_STATUS = (
        ('R', 'RECU'),
        ('P', 'PROFAMA FACTURE'),
        ('F', 'FACTURE'),
    )
    
    # Champs du modèle Invoice
    Costumer = models.ForeignKey(Costumer, on_delete=models.PROTECT)  # Client associé à la facture
    save_b = models.ForeignKey(User, on_delete=models.PROTECT)  # Utilisateur qui a enregistré la facture
    invoice_date_time = models.DateTimeField(auto_now_add=True)  # Date et heure de la facture
    invoice_type = models.CharField(max_length=1, choices=INNVOICE_STATUS)  # Type de la facture
    total = models.DecimalField(max_digits=500, decimal_places=2)# Total de la facture
    last_update = models.DateTimeField(null=True, blank=True)  # Dernière mise à jour de la facture
    paid = models.BooleanField(default=False)  # Indique si la facture est payée
    comment = models.TextField(null=True, max_length=1000, blank=True)  # Commentaire sur la facture

    class Meta:
        db_table = ''  # Nom de la table dans la base de données
        managed = True  # Indique si Django doit gérer la table
        verbose_name = 'Invoice'  # Nom singulier du modèle
        verbose_name_plural = 'Invoices'  # Nom pluriel du modèle

    def __str__(self):
        return self.invoice_date_time, self.Costumer.name  # Représentation en chaîne de caractères du modèle
    @property
    def get_total(self):
        articles = self.article_set.all()   
        total = sum(article.get_total for article in articles)
        return total    



# Modèle représentant un article dans une facture
class Article(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name='articles')
    name = models.CharField(max_length=255)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=1000, decimal_places=2)
    class Meta:
        db_table = ''  # Nom de la table dans la base de données
        managed = True  # Indique si Django doit gérer la table
        verbose_name = 'Article'  # Nom singulier du modèle
        verbose_name_plural = 'Articles'  # Nom pluriel du modèle

    @property
    def get_total(self):
        total = self.quantity * self.unit_price   
        return total   

templates/add_Costumer.html
{% extends 'base.html' %}
{% load i18n %} <!-- Charge le module de traduction -->
{% block content %}
<br><br>
<h1 class="text-capitatlizer text-center  mx-10 bg-dark text-white">Register a new customer</h1>
<form method="POST" class="mx-5">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-6" >
            <label for="name">Name</label>
            <input type="text" required class="form-control" name="name" id="name" placeholder="customer first name and last name"> 
        </div>
        <div class="form-group col-md-6" >
            <label for="email">Email</label>
            <input type="email" required class="form-control" name="email" id="email" placeholder="customer email"> 
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6" >
            <label for="phone">Phone</label>
            <input type="number" class="form-control" name="phone" id="phone" placeholder="customer phone number">
     </div>
    <div class="form-group col-md-6" >
        <label for="state">State</label>
        <select name="state" required id="state" class="form-control">
            <option value="Cameroon">Cameroon</option>
            <option value="England">England</option>
            <option value="Gemarny">Gemarny</option>
            <option value="France">France</option>
            <option value="USA">USA</option>
            <option value="Portugal">Portugal</option>
        </select>
    </div>
   
</div>
<div class="form-row">
    
    <div class="form-group col-md-6" >
        <label for="address">Adress</label> 
        <input type="text" required class="form-control" name="address" id="address" placeholder="customer adress">
    </div>
    <div class="form-group col-md-6" >
        <label for="sex">Sex</label> 
        <select required name="sex"  id="sex" class="form-control">
            <option value="M">Male</option>
            <option value="F">Femele</option>
        </select>
    </div>
</div>    
<div class="form-row">
    <div class="form-group col-md-6" >
        <label for="city">City</label> 
        <input type="text" required class="form-control" name="city" id="city" placeholder="customer city">
    </div>
    <div class="form-group col-md-6" >
        <label for="Zip">Zip code</label> 
        <input type="text" required class="form-control" name="Zip" id="Zip" placeholder="customer Zip code">
    </div>    
</div>
   <button type="submit" class="btn btn-primary text-center">Save</button> 
</form>
<br><br>
{% endblock content %} 

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %} <!-- Charge le module de traduction -->
{% block content %}
<br><br>

<!-- Section des boutons pour ajouter une facture ou un client -->
<div class="row">
   <!-- Bouton pour ajouter une nouvelle facture -->
   <a href="{% url 'add_invoice' %}" class="btn col-md-4 btn-primary">
      {% trans 'Register a new invoice' %}<span class="badge text-bg-secondary"></span>
   </a>

   <!-- Bouton vide (peut être utilisé pour une autre action) -->
   <a href='#' class="col-md-4">
      <span class="badge text-bg-secondary"></span>
   </a>

   <!-- Bouton pour ajouter un nouveau client -->
   <a href="{% url 'add_customer' %}" class="btn col-md-4 btn-primary">
      {% trans 'Register a new customer' %}<span class="badge text-bg-secondary"></span>
   </a>
</div>

<br> <br>

<!-- Champ de recherche -->
<div class="form-group ">
   <!-- Champ de saisie pour rechercher dans le tableau -->
   <input id="search" class="form-control" type="text" placeholder="{% trans 'Search...' %}">
</div>

<!-- Tableau des factures -->
<div>
   <table class="table table-striped-columns">
      <thead>
         <tr>
            <!-- En-têtes des colonnes du tableau -->
            <th scope="col">#</th>
            <th scope="col">{% trans 'CUSTOMERS NAME' %}</th>
            <th scope="col">{% trans 'DATE' %}</th>
            <th scope="col">{% trans 'TOTAL' %}</th>
            <th scope="col">{% trans 'PAID' %}</th>
            <th scope="col">{% trans 'TYPE OF INVOICE' %}</th>
            <th scope="col">{% trans 'ACTION' %}</th>
         </tr>
      </thead>
      <tbody id="myTable">
         {% if invoices %}
         <!-- Boucle pour afficher chaque facture -->
         {% for facture in invoices %}
         <tr>
            <th scope="row">{{ facture.pk }}</th>
            <td>{{facture.Costumer.name}}</td>
            <td>{{facture.invoice_date_time}}</td>
            <td>{{ facture.total}}</td>
            <td>
               <!-- Affiche une icône selon que la facture est payée ou non -->
               {% if facture.paid %}
               <img src="{% static 'images/icon-yes.svg' %}" alt="{% trans 'True' %}">
               {% else %}
               <img src="{% static 'images/icon-no.svg' %}" alt="{% trans 'False' %}">
               {% endif %}
            </td>
            <td>{{facture.get_invoice_type_display }}</td>
            <td>
               <!-- Bouton pour afficher les détails de la facture -->
               <a href="{% url 'InvoiceDetailView' pk=facture.pk %}" title="{% trans 'Detail' %}" class="badge text-white bg-success">{% trans 'View' %}</a>

               <!-- Bouton pour ouvrir le modal de suppression -->
               <button id="btn-invoice-sup" type="button" data-toggle="modal" data-target="#supprimer"
                  class="badge text-white bg-danger" title="{% trans 'Delete' %}" data-id="{{ facture.pk }}"
                  data-customer="{{facture.customer.name}}">{% trans 'Delete' %} 
               </button>

               <!-- Bouton pour ouvrir le modal de modification -->
               <button id="btn-invoice-mod" type="button" data-toggle="modal" title="{% trans 'Modify' %}" data-target="#modifier"
                  data-id="{{facture.pk}}" data-customer="{{facture.customer.name}}"
                  class="badge text-dark bg-warning">{% trans 'Modify' %}
               </button>
            </td>
         </tr>
         {% endfor %}

         <!-- Pagination -->
         {% if invoices.has_other_pages %}
         <div class="btn-group" role="group" aria-label="{% trans 'Item pagination' %}">
            <!-- Bouton pour aller à la page précédente -->
            {% if invoices.has_previous %}
            <a href="?page={{ invoices.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
            {% endif %}
            <!-- Boucle pour afficher les numéros de page -->
            {% for i in invoices.paginator.page_range %}
               {% if invoices.number == i %}
               <a href="?page={{ i }}" class="btn btn-primary">{{ i }}</a>
               {% else %}
               <a href="?page={{ i }}" class="btn btn-outline-primary">{{ i }}</a>
               {% endif %}
            {% endfor %}
            <!-- Bouton pour aller à la page suivante -->
            {% if invoices.has_next %}
            <a href="?page={{ invoices.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
            {% endif %}
         </div>
         {% endif %}
         {% else %}
         <!-- Message si aucune facture n'est trouvée -->
         <p class="text-center text-white">{% trans 'No invoice found.' %}</p>
         {% endif %}
      </tbody>
   </table>
</div>

<!-- Modal pour modifier une facture -->
<div class="modal fade" id="modifier" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark text-center" id="exampleModalLabel">{% trans 'Modification' %}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="{% trans 'Close' %}">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <form method="post">
            {% csrf_token %}
            <div class="modal-body">
               <!-- Champ caché pour stocker l'ID de la facture à modifier -->
               <input name="id_modified" type="hidden" id="id_modified">
               <label id="label_id" class="text-dark checkbox-inline"> <strong id="strong_id">{% trans 'This bill has been paid?' %}</strong></label>
               <!-- Options pour indiquer si la facture est payée ou non -->
               <input type="radio" id="html" name="modified" value="True">
               <label class="text-white bg-primary" for="html">{% trans 'Yes' %}</label>
               <input type="radio" id="css" name="modified" value="False">
               <label class="text-white bg-danger" for="css">{% trans 'No' %}</label><br>
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Close' %}</button>
               <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
            </div>
         </form>
      </div>
   </div>
</div>

<!-- Modal pour supprimer une facture -->
<div class="modal fade" id="supprimer" tabindex="-1" role="dialog" aria-labelledby="sexampleModalLabel"
   aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark" id="sexampleModalLabel">{% trans 'Delete Invoice' %}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="{% trans 'Close' %}">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <form method="post">
               {% csrf_token %}
               <!-- Champ caché pour stocker l'ID de la facture à supprimer -->
               <input name="id_supprimer" type="hidden" id="id_supprimer">
               <label id="label_id_s" class="text-dark checkbox-inline"> <strong id="strong_id_s">{% trans 'Are you sure you want to delete the invoice?' %}</strong></label>
               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Close' %}</button>
                  <button type="submit" class="btn btn-danger">{% trans 'Delete' %}</button>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>

<br><br>
<script>
   $(document).ready(function () {
      // Fonction pour filtrer les lignes du tableau en fonction de la recherche
      $("#search").on("keyup", function () {
         var value = $(this).val().toLowerCase(); // Récupère la valeur saisie et la convertit en minuscule
         $("#myTable tr").filter(function () {
            // Affiche ou masque les lignes en fonction de la correspondance
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
         });
      });
   });
   
   // modification

   $(document).on('click', '#btn-invoice-mod', function(){
      let invoice_id = $(this).data('id');
      let customer = $(this).data('customer');
      $('#id_modified').val(invoice_id);

   })

   // deleting of invoice

   $(document).on('click', '#btn-invoice-sup', function(){
      let invoice_id = $(this).data('id');
      let customer = $(this).data('customer');
      $('#id_supprimer').val(invoice_id);

   })



</script>
{% endblock %}

templates/invoice-template.html
{% extends "base.html" %}
{% load i18n %} <!-- Charge le module de traduction -->
{% load static %}

{% block content %}

<div class="container">
    <div class="row gutters">
    	<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    		<div class="card">
    			<div class="card-body p-0">
    				<div class="invoice-container">
    					<div class="invoice-header">
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
    								<div class="custom-actions-btns mb-5">
    									<a href="{% url 'invoice_pdf' pk=obj.pk %}" class="btn btn-primary">
    										<i class="icon-download"></i> Download
    									</a>
    									<a href="#" class="btn btn-secondary">
    										<i class="icon-printer"></i> Print
    									</a>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
    								<a href="https://web.facebook.com/?_rdc=1&_rdr#" class="invoice-logo">
    									Bakayoko Programmer
    								</a>
    							</div>
    							<div class="col-lg-6 col-md-6 col-sm-6">
    								<address class="text-right">
    									Bakayoko Programmer , West<br>
    									Cameroon, BANDJOUN<br>
    									00000 00000
    								</address>
    							</div>
    						</div>
    						<!-- Row end -->
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<address>
                                            {{ obj.Costumer.name }}<br>
                                            {{ obj.Costumer.address }}, {{ obj.Costumer.city }}, Cameroon
                                        </address>
    								</div>
    							</div>
    							<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<div class="invoice-num">
    										<div>{{obj.get_invoice_type_display}} - #00{{obj.id}}</div>
    										<div>{{obj.invoice_date_time}}</div>
    									</div>
    								</div>													
    							</div>
    						</div>
    						<!-- Row end -->
    
    					</div>
    
    					<div class="invoice-body">
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-lg-12 col-md-12 col-sm-12">
    								<div class="table-responsive">
    									<table class="table custom-table m-0">
    										<thead>
    											<tr>
    												<th>Items</th>
													<th>Product ID</th>
													<th>Quantities</th>
													<th>Unit Price</th>
													<th>Subtotal</th>
    											</tr>
    										</thead>
    										<tbody>
                                              {% for article in articles %}  
                                              
    											<tr>

                                                   

                                                    <td>
    													{{ article.name }}
    													
    												</td>

													<td>
    													{{ article.id }}
    													
    												</td>

													<td>
    													{{ article.quantity }}
    													
    												</td>

													<td>
    													{{ article.unit_price }}
    													
    												</td>

													<td>
    													{{ article.total }}
    													
    												</td>

                                                    
    												
    											</tr>
                                                {% empty %}
<tr>
        <td colspan="5">No articles found for this invoice.</td>
    </tr>    
                                               {% endfor %} 
    											
    											
    											<tr>
    												<td>Comment: {{obj.comment}}</td>
    												<td colspan="2">
														<p>
															Subtotal<br>
															Shipment &amp; Handling<br>
															Tax<br>
														</p>
    													<h5 class="text-success"><strong>Total</strong></h5>
    												</td>			
    												<td>
    													<p>
    														{{obj.get_total}} FCFA<br>
    														00.00 FCFA<br>
    														00.00 FCFA<br>
    													</p>
    													<h5 class="text-success"><strong>${{obj.get_total}} FCFA</strong></h5>
    												</td>
                                                    <td> 
                                                            PAID:                    

                                                        {% if obj.paid  %}

                                                           <img class="icon" src="{% static 'images/icon-yes.svg' %}" alt="True">
                                                        {% else %}
                                                            <img class="icon" src="{% static 'images/icon-no.svg' %}" alt="False">
   
                                                        {% endif %}
                                                    </td>
    											</tr>
    										</tbody>
    									</table>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->
    
    					</div>
    
    					<div class="invoice-footer">
    						Thank you for your purchase .
    					</div>
    
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>
{% endblock content %}

templates/invoicepdf.html
<!DOCTYPE html>
{% load i18n %} <!-- Charge le module de traduction -->
{% block title %}Invoice PDF{% endblock title %}
{% block styles %}
{% endblock styles %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
</head>
<body>
    

{% block content %}

<div class="container">
    <div class="row gutters">
    	<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    		<div class="card">
    			<div class="card-body p-0">
    				<div class="invoice-container">
    					<div class="invoice-header">
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
    								<a href="https://web.facebook.com/?_rdc=1&_rdr#" class="invoice-logo">
    									Bakayoko Programmer
    								</a>
    							</div>
    							<div class="col-lg-6 col-md-6 col-sm-6">
    								<address class="text-right">
    									Bakayoko Programmer , West<br>
    									Cameroon, BANDJOUN<br>
    									00000 00000
    								</address>
    							</div>
    						</div>
    						<!-- Row end -->
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<address>
                                            {{ obj.Costumer.name }}<br>
                                            {{ obj.Costumer.address }}, {{ obj.Costumer.city }}, Cameroon
                                        </address>
    								</div>
    							</div>
    							<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<div class="invoice-num">
    										<div>{{obj.get_invoice_type_display}} - #00{{obj.id}}</div>
    										<div>{{obj.invoice_date_time}}</div>
    									</div>
    								</div>													
    							</div>
    						</div>
    						<!-- Row end -->
    
    					</div>
    
    					<div class="invoice-body">
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-lg-12 col-md-12 col-sm-12">
    								<div class="table-responsive">
    									<table class="table custom-table m-0">
    										<thead>
    											<tr>
    												<th>Items</th>
													<th>Product ID</th>
													<th>Quantities</th>
													<th>Unit Price</th>
													<th>Subtotal</th>
    											</tr>
    										</thead>
    										<tbody>
                                              {% for article in articles %}  
                                              
    											<tr>

                                                   

                                                    <td>
    													{{ article.name }}
    													
    												</td>

													<td>
    													{{ article.id }}
    													
    												</td>

													<td>
    													{{ article.quantity }}
    													
    												</td>

													<td>
    													{{ article.unit_price }}
    													
    												</td>

													<td>
    													{{ article.total }}
    													
    												</td>

                                                    
    												
    											</tr>
                                                {% empty %}
<tr>
        <td colspan="5">No articles found for this invoice.</td>
    </tr>    
                                               {% endfor %} 
    											
    											
    											<tr>
    												<td>Comment: {{obj.comment}}</td>
    												<td colspan="2">
														<p>
															Subtotal<br>
															Shipment &amp; Handling<br>
															Tax<br>
														</p>
    													<h5 class="text-success"><strong>Total</strong></h5>
    												</td>			
    												<td>
    													<p>
    														{{obj.get_total}} FCFA<br>
    														00.00 FCFA<br>
    														00.00 FCFA<br>
    													</p>
    													<h5 class="text-success"><strong>${{obj.get_total}} FCFA</strong></h5>
    												</td>
                                                    <td> 
                                                            PAID:                    

                                                        {% if obj.paid  %}
														<p class="text-success font-weight-bold">Yes, the invoice is paid.</p>
                                                        {% else %}
                                                            {% comment %} <img class="icon" src="{% static 'images/icon-no.svg' %} " alt="False"> {% endcomment %}
														<p class="text-danger font-weight-bold">No, the invoice is not paid.</p>
                                                        {% endif %}
                                                    </td>
    											</tr>
    										</tbody>
    									</table>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->
    
    					</div>
    
    					<div class="invoice-footer">
    						Thank you for your purchase{{date}} .
    					</div>
    
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>
{% endblock content %}
</body>  
</html>  